import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'edge';

const HARD_EXCLUDED_TERMS = [
  'official music video',
  'music video',
  ' mv ',
  '(mv)',
  '[mv]',
  '#shorts',
];

const SOFT_EXCLUDED_TERMS = [
  'official video',
  'video klip',
  'lyric video',
  'live',
  'concert',
  'performance',
  'reaction',
  'teaser',
  'trailer',
  'karaoke',
  'cover',
];

const PREFERRED_TERMS = ['official audio', 'audio', 'topic', 'provided to youtube by', 'auto-generated by youtube'];

function normalizeText(text: string) {
  return ` ${text.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim()} `;
}

function sanitizeTitle(text: string) {
  return normalizeText(text)
    .replace(/\b(official|music|video|mv|lyric|live|performance|audio|visualizer|karaoke)\b/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function isTopicChannel(channelTitle: string) {
  const normalized = normalizeText(channelTitle).trim();
  return normalized.endsWith(' topic') || normalized.includes(' - topic');
}

function scoreCandidate(item: any, expectedTitle: string, expectedArtist: string) {
  const title = item?.snippet?.title ?? '';
  const description = item?.snippet?.description ?? '';
  const channelTitle = item?.snippet?.channelTitle ?? '';
  const text = normalizeText(`${title} ${description} ${channelTitle}`);
  const expectedTitleNormalized = sanitizeTitle(expectedTitle);
  const candidateTitleNormalized = sanitizeTitle(title);
  const expectedArtistNormalized = normalizeText(expectedArtist).trim();
  const topic = isTopicChannel(channelTitle);

  // Exclude hard music-video indicators
  if (HARD_EXCLUDED_TERMS.some((term) => text.includes(` ${normalizeText(term).trim()} `))) return -999;

  let score = 0;

  // Prefer direct audio uploads / topic channels
  PREFERRED_TERMS.forEach((term) => {
    if (text.includes(` ${normalizeText(term).trim()} `)) score += 6;
  });
  if (topic) score += 120;

  // Down-rank non-direct song formats
  SOFT_EXCLUDED_TERMS.forEach((term) => {
    if (text.includes(` ${normalizeText(term).trim()} `)) score -= 8;
  });

  // Prioritize clean title match (usually Topic upload title is plain).
  if (expectedTitleNormalized && candidateTitleNormalized === expectedTitleNormalized) score += 80;
  else if (expectedTitleNormalized && candidateTitleNormalized.startsWith(expectedTitleNormalized)) score += 40;

  // Keep artist relevance strong.
  if (expectedArtistNormalized && text.includes(` ${expectedArtistNormalized} `)) score += 20;

  // Slightly prefer shorter direct-song uploads over long intros.
  const duration = item?.contentDetails?.duration as string | undefined;
  if (duration) {
    const isLongForm = /PT(\d+H|\d{2,}M)/.test(duration);
    if (isLongForm) score -= 3;
  }

  return score;
}

/**
 * GET /api/search/youtube?q=...
 * 
 * Proxy ke YouTube Data API v3 untuk mencari videoId.
 * Menggunakan Edge Runtime untuk performa maksimal.
 */
export async function GET(request: NextRequest) {
  const title = request.nextUrl.searchParams.get('title')?.trim() ?? '';
  const artist = request.nextUrl.searchParams.get('artist')?.trim() ?? '';
  const query = request.nextUrl.searchParams.get('q');
  
  if (!query?.trim() && !title) {
    return NextResponse.json({ error: 'Query or title is required' }, { status: 400 });
  }

  const API_KEY = process.env.YOUTUBE_API_KEY;
  
  if (!API_KEY) {
    console.error('YOUTUBE_API_KEY is missing');
    return NextResponse.json({ error: 'Server configuration error' }, { status: 500 });
  }

  try {
    const searchQuery = query?.trim() || `${title} ${artist} topic`.trim();
    const url = `https://www.googleapis.com/youtube/v3/search?part=id,snippet&maxResults=12&q=${encodeURIComponent(searchQuery)}&type=video&videoCategoryId=10&key=${API_KEY}`;
    
    const res = await fetch(url);
    const data = await res.json();

    if (data.error) {
      console.error('YouTube API Error:', data.error);
      return NextResponse.json({ error: data.error.message }, { status: 500 });
    }

    const items = Array.isArray(data.items) ? data.items : [];
    const ranked = items
      .map((item: any) => ({ item, score: scoreCandidate(item, title, artist) }))
      .filter((entry: { item: any; score: number }) => entry.score > -999)
      .sort((a: { score: number }, b: { score: number }) => b.score - a.score);

    const rankedTopicOnly = ranked.filter((entry: { item: any }) =>
      isTopicChannel(entry.item?.snippet?.channelTitle ?? '')
    );
    const bestTopic = rankedTopicOnly[0]?.item?.id?.videoId;
    const videoId = bestTopic ?? ranked[0]?.item?.id?.videoId ?? items[0]?.id?.videoId;

    if (!videoId) {
      return NextResponse.json({ error: 'No video found' }, { status: 404 });
    }

    return NextResponse.json({ videoId });
  } catch (error: any) {
    console.error('YouTube search failed:', error.message);
    return NextResponse.json({ error: 'Failed to search YouTube' }, { status: 500 });
  }
}
