import { Song } from '@/types/music';
import { RadioMeta } from '@/types/player/engine';
import { DeviceInfo } from '@/types/connect';

export interface PlayerContextType {
  currentTrack: Song | null;
  isPlaying: boolean;
  isResolving: boolean;
  isPreview: boolean;
  isGuestPreview: boolean;
  isRadio: boolean;
  radioMeta: RadioMeta | null;
  isError: boolean;
  currentTime: number;
  duration: number;
  volume: number;
  queue: Song[];
  queueIndex: number;
  isShuffled: boolean;
  repeatMode: 'none' | 'all' | 'one';
  isAutoplayEnabled: boolean;
  toggleShuffle: () => void;
  cycleRepeatMode: () => void;
  playTrack: (track: Song, queue?: Song[], target?: number | string) => void;
  togglePlay: () => void;
  nextTrack: () => void;
  prevTrack: () => void;
  seek: (time: number) => void;
  setVolume: (volume: number) => void;
  addToQueue: (track: Song) => void;
  playNext: (track: Song) => void;
  removeFromQueue: (trackId: string) => void;
  promoteToManual: (trackId: string) => void;
  clearQueue: () => void;
  reorderQueue: (startIndex: number, endIndex: number) => void;
  shufflePlay: (tracks: Song[]) => void;
  sleepTimerEndTime: number | null;
  setSleepTimer: (minutes: number) => void;
  clearSleepTimer: () => void;
  toggleAutoplay: () => void;
  myTabId: string;
  activeTabId: string | null;
  isActivePlayer: boolean;
  connectedDevices: DeviceInfo[];
  autoplayBlocked: boolean;
  isElecting: boolean;
  transferPlayback: (targetTabInstanceId: string) => void;
  renameDevice: (newName: string) => void;
  dismissAutoplayBlock: () => void;
}
